- name: app setup
  ansible.builtin.import_role:
    name: common
    task_from: app-setup.yaml
- name: nodejs installation
  ansible.builtin.import_role:
    name: common
    task_from: nodejs.yaml
- name: mongo app setup
  ansible.builtin.import_role:
    name: common
    task_from: mongodb-setup
- name: system app setup
  ansible.builtin.import_role:
    name: common
    task_from: systemd.yaml