- name: "stop the {{component}}"
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: stopped
- name: remove old code
  tags:
  - deployment
  ansible.builtin.file:
    path: /app/*
    state: absent
    force: yes
