- name: copying mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: download mongodb
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present
- name: get the entries count
  ansible.builtin.command: mongo --host mongodb.infome.website --quiet --eval 'db=db.getSiblingDB("catalogue");db.products.count()'
  register: entries_count
  when: {{component}}=="catalogue"

- name: get the entries count
  ansible.builtin.command: mongo --host mongodb.infome.website --quiet --eval 'db=db.getSiblingDB("user");db.users.count()'
  register: entries_count
  when: {{component}}=="users"

- name: load DB schema
  ansible.builtin.shell: "mongo --host mongodb.infome.website < /app/schema/{{component}}.js"
  when: entries_count.stdout == "0"
